//review
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILED = 'CREATE_REVIEW_FAILED';

//person
export const FETCH_LEADERBOARD = "FETCH_LEADERBOARD";
export const FETCH_LEADERBOARD_SUCCESS = "FETCH_LEADERBOARD_SUCCESS";
export const FETCH_LEADERBOARD_FAILED = "FETCH_LEADERBOARD_FAILED";

//routes
export const FETCH_OTHER_USERS_ROUTES = 'FETCH_OTHER_USERS_ROUTES';
export const FETCH_OTHER_USERS_ROUTES_SUCCESS = 'FETCH_OTHER_USERS_ROUTES_SUCCESS';
export const FETCH_OTHER_USERS_ROUTES_FAILED = 'FETCH_OTHER_USERS_ROUTES_FAILED';
export const FETCH_ROUTE_TYPES = 'FETCH_ROUTE_TYPES';
export const FETCH_ROUTE_TYPES_SUCCESS = 'FETCH_ROUTE_TYPES_SUCCESS';
export const FETCH_ROUTE_TYPES_FAILED = 'FETCH_ROUTE_TYPES_FAILED';
export const FETCH_ROUTE_PURPOSES = 'FETCH_ROUTE_PURPOSES';
export const FETCH_ROUTE_PURPOSES_SUCCESS = 'FETCH_ROUTE_PURPOSES_SUCCESS';
export const FETCH_ROUTE_PURPOSES_FAILED = 'FETCH_ROUTE_PURPOSES_FAILED';
export const FETCH_ROUTE_WEATHER_TYPES = 'FETCH_ROUTE_WEATHER_TYPES';
export const FETCH_ROUTE_WEATHER_TYPES_SUCCESS = 'FETCH_ROUTE_WEATHER_TYPES_SUCCESS';
export const FETCH_ROUTE_WEATHER_TYPES_FAILED = 'FETCH_ROUTE_WEATHER_TYPES_FAILED';
export const FETCH_UPLOADED_ROUTES = 'FETCH_UPLOADED_ROUTES';
export const FETCH_UPLOADED_ROUTES_SUCCESS = 'FETCH_UPLOADED_ROUTES_SUCCESS';
export const FETCH_UPLOADED_ROUTES_FAILED = 'FETCH_UPLOADED_ROUTES_FAILED';
export const UPLOAD_UNSAVED_ROUTES = 'UPLOAD_UNSAVED_ROUTES';
export const UPLOAD_UNSAVED_ROUTES_SUCCESS = 'UPLOAD_UNSAVED_ROUTES_SUCCESS';
export const UPLOAD_UNSAVED_ROUTES_FAILED = 'UPLOAD_UNSAVED_ROUTES_FAILED';
export const ADD_UNSAVED_ROUTE = 'ADD_UNSAVED_ROUTE';

//route recording
export const START_RECORDING_ROUTE = 'START_RECORDING_ROUTE';
export const STOP_RECORDING_ROUTE = 'STOP_RECORDING_ROUTE';
export const CHANGE_ROUTE_RECORDING_STATE = 'CHANGE_ROUTE_RECORDING_STATE';

//login
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const lOG_OUT_SUCCESS = 'lOG_OUT_SUCCESS';
export const LOG_OUT_FAIL = 'LOG_OUT_FAIL';
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHANGE_USER_STORE_SETTINGS = 'CHANGE_USER_STORE_SETTINGS';

//route
export const ADD_ROUTE_POINT = 'ADD_ROUTE_POINT';